<footer>
  <div class="con">
    <div class="social-icons">
      <a href="https://www.facebook.com/profile.php?id=100071687532300"><i class="fab fa-facebook-f"></i></a>
      <a href="https://wa.me/60189754948"><i class="fab fa-whatsapp"></i></a>
      <a href="https://www.instagram.com/jimmmms0/"><i class="fab fa-instagram"></i></a>
      <a href="https://www.youtube.com/channel/UC_KQS9_jAU8HPzRMLGPLPjA"><i class="fab fa-youtube"></i></a>
    </div>  
    <div class="contact-info">
      <p>Contact me at: j21034891@student.newinti.edu.my</p>
      <p>Dück &copy; 2023</p>
    </div>
  </div>
</footer>
