<nav>
  <ul>
    <li><a href="index.php">Home</a></li>
    <li><a href="product.php">Product</a></li>
    <li><a href="enquire.php">Enquire</a></li>
    <li><a href="about.php">About</a></li>
    <li class="dropdown">
      <a href="#" class="dropbtn">Enhancements</a>
      <div class="dropdown-content">
        <a href="enhancements.php">Enhancements 1</a>
        <a href="enhancements2.php">Enhancements 2</a>
        <a href="enhancements3.php">Enhancements 3</a>
      </div>
    </li>
    <li><a href="manager.php">Manager</a></li>
  </ul>
</nav>
  </div>
</header>
