<nav>
  <ul>
    <li><a href="indexguest.php">Home</a></li>
    <li class="dropdown">
      <a href="#" class="dropbtn">Join Now |Sign In</a>
      <div class="dropdown-content">
        <a href="customerlogin.php">Customer Login</a>
        <a href="customerregister.php">Customer Register</a>
        <a href="managerstafflogin.php">Manager/Staff Login</a>
      </div>
    </li>
  </ul>
</nav>
  </div>
</header>
